### ISSUE TITLE
More data

### ISSUE THREAD

**Issue by khwilson** [khwilson/RedrawStates#12]
Is there a good source of county level election data for pre-2012? If so, it'd be nice to have the tool be able to go further back in time.

**Comment by khwilson** [comment]
Mapbox has some tilesets going back to 2004 (h/t Will Poundstone) https://www.mapbox.com/elections/tilesets

**Comment by hotdogPi** [comment]
Someone seems to have made a copy of your tool https://redraw-america.github.io which has data from 2000 to 2016. I don't know what data they used. They fixed Virginia in a different way from what you did, holding Q doesn't work, and they haven't updated to 2020 yet (nor have they made their polygons more detailed). Their 2016 data has been the official tally long before you updated yours.

**Comment by khwilson** [comment]
Always good to see people taking tools and updating them for their needs.
Maintaining software is hard. :-)

The q thing was actually something I just implemented based on a suggestion
from people on Twitter, so that's just a 2020 Edition feature.

They seem to have used the MIT data as well, so that seems pretty good. One
thing about the polygons as well is to really make this work right you
probably want to have multiple different levels of resolution in the
topojson. However, that's beyond the amount of time I have to dedicate to
this project now.

**Comment by khwilson** [comment]
Okiedokes, for reference, I've fixed up all the data on the main page going back to 2004. The 1990 SF1 is seemingly difficult to find at the moment, but barring that I could add 2000.

Anyway, happy playing around!
