### ISSUE TITLE
Pennsylvania has 20 electoral votes not 21.

### ISSUE THREAD

**Issue by electoraluniversity** [khwilson/RedrawStates#2]
Close

**Comment by khwilson** [comment]
I'm not sure I see where the 21 votes is coming up. Love to fix, but can you give an example of where it's showing up in the summation?

Also, yeah, the problem with ME-2 is that as people start redrawing states, they'll eventually empty out ME of enough people to give ME only 1 vote; or they'll add so many that they get a third vote. The instructions do clearly state that ME and Nebraska's different style aren't accounted for. If you have a nice way of bridging the gap, I'm more than happy to implement it.
