### ISSUE TITLE
Can't select Virginia Independent Cities

### ISSUE THREAD

**Issue by Fleetlord** [khwilson/RedrawStates#6]
When trying to redraw in the Virginia area, there's a frustrating problem where some of Virginia's Independent cities (e.g. Franklin, Fredricksburg) are visible on the map, but completely unselectable (I even opened the code explorer in desperation, but couldn't seem to find them.

Is it possible to make these tiny "counties" select-able, if only from a list? Or alternately to just fold the cities into the nearest county?

See [here](http://kevinhayeswilson.com/redraw/?share=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabcccccccccccccccdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddeeeeeeeeeeeeCeCeeeCeeeeeeeeeeCeeCeeCCeeCeCeeeeeeeeeeeeeCeeffffqqfffqfffqfSfSffqqfSffffqffqqfffqqBSfSSSYqffBfqqSffffSBffqYqgggggggghhhikkakkjajkkjkjkkakakkjakjjkjjakakkkjkkakjkjjjkajjjjkjjkkjajkkkkkkkaakkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkllZllmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnoooooooooooooooooooooooooooooooooooooooooooonooooooooooooooooooooooooooooooooooooooooooooooopppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssttttttttttttttttuuuuuuuuuuuuuuuuuuuuuuuuvDvvtDDDtvvvvDwXowXwXowXooooXwXXowXXoXwwXXowXwwowXowoXoXXwXwwXXwXXXoXwXwowoowowXXwwowwwwowXwwowwXxxIIIIPPxIIIxIIxPIxxIPxPxIxxIxIPxIIIPxIxPPIIIPIxIxPIPIxIIxPIIxIPIxPIxxIIIxIIIIxIxxPIxIPyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBeCeeeeeeeeeeeeeeeDDDDDDDttDEEEEEEEEEEEEEEEEEEEEEFFFFFFFFFFFFFFFFFFFFFfFFFFFFFfFFFGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIJJJJJJJJJJJJJJJJJwJJJwJJJJJJJJJJJJJJJJJJJJJJJJwwJJJJJJJJJJJJJwJJJJJJJJJwJJJJJJJJJJJJJJwJKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLMMMMMEMMEMMMMMEMMMMMMMEMMMMMMMMMMMMEMMEMMMMMEEMEMMEEMMMMMMMMMMMMMMMNNNNNOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQRRRRRRRRRRRRRRRRRRRRRFRFRRRRRRFRRRRRRRRRRRRRRRRRRRRRRRFRRRRRRRRFRFRRRRFRRRRRRRRRRFRRRRRRRRRRRRRRRRRRRRRRRRRFRRRRRRFRRRRRRFRFFRRRRRFRRRRFFRRRRFRRRRRRRRFRRRRRRRRRRFRRRRRRRRRRRRRRRRRRRRRRRFRRFRRRRRFRRRRRRRRRRRRRRRRRRFRRRRRRRFRRRRRRRRRRFRRRRFRFRRRRFRRFRRRRFFSSSSSSSSSSSSSSSSSSSSSSSSSSSSSTTTTTTTTTTTTTTuUUUUUUUUUUUUUUUuUuUUuUUUUUuuuUUUuUuUUUUUuuUUuuuuuuUuUUUuUuUUuuuUUUUUUUuuUUuUUUUUUUuuuuuUUUuUUUUZUUUuUUUUUUUUUUUUUUUUUuUUUUUUuUUUuuUuUVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVWuWWWWWWWWWWWWWWWWuWWWWWWWWWWWWWuWWWWWWWWWWWWWWWWWWWWWWXxXxXXXXXXXXnXXxXXXXXXnXXXXXXnXXXXXXXXXXnXXXXXXXXXXnXnXXXXXXXXXXnXXXXXXXYYYYYYYYYYYYYYYYYYYYYYY) for an example of independent cities ruining my nice uber-Maryland.

**Comment by khwilson** [comment]
Hi there! Thanks for the interest.

Several folks have raised this issue. I'm planning on simply merging the cities with the counties. Didn't get time to do it yesterday, but if you get a chance and want to post the updated data file, I'd appreciate it. Else, I'll get a chance tonight.

**Comment by khwilson** [comment]
Totally right. Tracking now in #11
