### ISSUE TITLE
Wyoming does not go away

### ISSUE THREAD

**Issue by Eunoia** [khwilson/RedrawStates#7]
Hey Kevin,

I'm a huge fan of the redraw states visualization you've made.

You've been able to to show just how janky the electoral college is, in a way that makes it really easy(and fun) to comprehend. 

I've spend way too much time playing with RedrawStates, and I noticed a small bug:

> Wyoming does not go away

In this gif, I've moved all of Wyoming's counties to it's neighbors. In the last batch of counties to move, the border of Wyoming never completely goes away.

![bye_wy](https://cloud.githubusercontent.com/assets/934880/21252904/77e4f174-c30f-11e6-8fbc-76643905f63d.gif)

This 'remaining borders' issue only happens in Wyoming. 

In merging other state's borders, the merged states's borders disappear, like Iowa in this screenshot

![iowa_no_morowa](https://cloud.githubusercontent.com/assets/934880/21253008/1ababe9c-c310-11e6-8b93-b8faf5195770.png)

In the table below the map, the population and vote counts for are all zero. 

![bye_wy_pop](https://cloud.githubusercontent.com/assets/934880/21253038/540b8140-c310-11e6-9c1f-d09e6678c117.png)

The best way I've found to cycle though the 'hide counties' button, which removes all the paths, and calls update(), which redraws state borers. However, this is rather slow. 

I'd love to be able to merge Wyoming into other states, but I'm not sure how to fix this. 

Any ideas?

**Comment by khwilson** [comment]
Oh how strange! It almost certainly has something to do with the fact that WY is last. But I'm not sure what. I'm quite tired at the moment, but I'll take a look tomorrow and see if I come up with anything!

Thanks for the interest in the tool! Glad you enjoyed it.
