### ISSUE TITLE
Moblie App?

### ISSUE THREAD

**Issue by Shi1222** [khwilson/RedrawStates#9]
I like this!  Maybe you Could  develop an mobile app so We can play it on The tablet?

**Comment by khwilson** [comment]
Thank you for the interest. I also think using this on a tablet would be really cool, but it would require remaking a lot of the code, which I don't have time for. If I got a grant to do so, perhaps I could, but for now, I don't have enough time.

However, if you want to work on the development, I'm more than happy to take pull requests!

Best,

Kevin
